=== steve-fryatt/xmlman/test/manual.dtd
<!-- Manual -->

<!ELEMENT manual (title, breadcrumb?, icons?, resources?, index?, chapter*)>
<!ATTLIST manual version CDATA #REQUIRED>

<!-- Breadcrumb -->

<!ELEMENT breadcrumb (dir*)>

<!ELEMENT dir (#PCDATA)>

<!-- Icons -->

<!ELEMENT icons (zip?, armv7?, iyonix?)>

<!ELEMENT zip (#PCDATA)>
<!ATTLIST zip alt CDATA #IMPLIED>
<!ATTLIST zip width CDATA #REQUIRED>
<!ATTLIST zip height CDATA #REQUIRED>

<!ELEMENT armv7 (#PCDATA)>
<!ATTLIST armv7 alt CDATA #IMPLIED>
<!ATTLIST armv7 width CDATA #REQUIRED>
<!ATTLIST armv7 height CDATA #REQUIRED>

<!ELEMENT iyonix (#PCDATA)>
<!ATTLIST iyonix alt CDATA #IMPLIED>
<!ATTLIST iyonix width CDATA #REQUIRED>
<!ATTLIST iyonix height CDATA #REQUIRED>

<!-- Index and Chapter -->

<!ELEMENT index (filename?, title?, resources?, chapterlist?, section*)>
<!ATTLIST index id CDATA #REQUIRED>

<!ELEMENT chapter (filename?, title?, resources?, summary?, section*)>
<!ATTLIST chapter id CDATA #REQUIRED>

<!ELEMENT filename (#PCDATA)>

<!ELEMENT chapterlist (EMPTY)>

<!ELEMENT section (title?, p*, table*, code*, image*, download*)>
<!ATTLIST section id CDATA #IMPLIED>

<!ELEMENT summary (#PCDATA)>
<!ELEMENT p (#PCDATA)>

<!-- Title -->

<!ELEMENT title (#PCDATA)>

<!-- Resources -->

<!ELEMENT resources (images?, downloads?, common?, chapters?)>

<!ELEMENT images (#PCDATA)>
<!ELEMENT downloads (#PCDATA)>
<!ELEMENT common (#PCDATA)>
<!ELEMENT chapters (#PCDATA)>

<!-- Entities -->

<!ENTITY ldquo "&amp;ldquo;">
<!ENTITY lsquo "&amp;lsquo;">
<!ENTITY minus "&amp;minus;">
<!ENTITY nbsp "&amp;nbsp;">
<!ENTITY ndash "&amp;ndash;">
<!ENTITY rdquo "&amp;rdquo;">
<!ENTITY rsquo "&amp;rsquo;">
<!ENTITY times "&amp;times;">





<!--
  <xsd:complexType name="TableType">
    <xsd:attribute name="id" type="xsd:string"/>
    <xsd:attribute name="title" type="xsd:string"/>
    <xsd:element name="columns" type="ColumnsType" minOccurs="1" maxOccurs="1"/>
    <xsd:element name="row" type="RowType" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:complexType>
   
  <xsd:complexType name="ColumnsType">
    <xsd:attribute name="align" type="xsd:string"/>
    <xsd:element name="col" type="ParagraphType" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:complexType>
  
  <xsd:complexType name="RowType">
    <xsd:element name="col" type="ParagraphType" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:complexType>
 
  <xsd:complexType name="CodeType">
    <xsd:attribute name="lang" type="xsd:string" use="required"/>
    <xsd:attribute name="file" type="xsd:string"/>
    <xsd:attribute name="id" type="xsd:string"/>
    <xsd:attribute name="title" type="xsd:string"/>
  </xsd:complexType>
  
  <xsd:complexType name="ImageType">
    <xsd:attribute name="file" type="xsd:string" use="required"/>
    <xsd:attribute name="id" type="xsd:string"/>
    <xsd:attribute name="title" type="xsd:string"/>
  </xsd:complexType>
  
  <xsd:complexType name="DownloadType">
    <xsd:attribute name="file" type="xsd:string" use="required"/>
    <xsd:attribute name="id" type="xsd:string"/>
    <xsd:attribute name="title" type="xsd:string"/>
    <xsd:attribute name="compatibility" type="xsd:string"/>
  </xsd:complexType>
 
  <xsd:complexType name="ParagraphType">
    <xsd:sequence>
      <xsd:element name="code" type="xsd:string"/>
      <xsd:element name="command" type="xsd:string"/>
      <xsd:element name="const" type="xsd:string"/>
      <xsd:element name="em" type="xsd:string"/>
      <xsd:element name="event" type="xsd:string"/>
      <xsd:element name="file" type="xsd:string"/>
      <xsd:element name="function" type="xsd:string"/>
      <xsd:element name="icon" type="xsd:string"/>
      <xsd:element name="intro" type="xsd:string"/>
      <xsd:element name="key" type="xsd:string"/>
      <xsd:element name="link" type="LinkType"/>
      <xsd:element name="maths" type="xsd:string"/>
      <xsd:element name="menu" type="xsd:string"/>
      <xsd:element name="mouse" type="xsd:string"/>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="reference" type="ReferenceType"/>
      <xsd:element name="swi" type="xsd:string"/>
      <xsd:element name="variable" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ReferenceType">
    <xsd:attribute name="id" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="LinkType">
    <xsd:attribute name="href" type="xsd:string" use="required"/>
  </xsd:complexType>
  -->

=== steve-fryatt/xmlman/test/test.xml
<?xml version='1.0'?>

<!DOCTYPE manual SYSTEM "manual.dtd">

<manual version="1.8.6">
<title>Wimp Programming In C</title>
<breadcrumb><dir>Home</dir><dir>Documentation</dir></breadcrumb>
<icons>
<zip    width  =  "34" height=    "34">../../software/images/zip.png</zip>
<armv7 alt
=
"ARMV7 OK" width    ="34" height="39">../../software/images/armv7.png</armv7>
<iyonix alt="Iyonix OK" width="34" height="39">../../software/images/iyonix.gif</iyonix>
</icons>
<resources none>
 <images>Images</images>
 <downloads>Downloads</downloads>
</resources>

<!-- Introduction -> -->

<section>
<p>This is a preliminary introduction.</p>
</section>

<!-- Index -->

<index>
<title>Manual Index</title>
<section>
<p>Like many other RISC&nbsp;OS users,   I started programming in
BBC&nbsp;BASIC. Although it served me well, I began to find that it
didn&rsquo;t always scale well &ndash; especially when software had to
handle large, variable amounts of data or   multiple documents.</p>

<p>After learning C on Unix systems, I began to investigate how it could be used on RISC&nbsp;OS. My first efforts directly copied the techniques used in BASIC, and quickly became just as unweildy as their predecessors.</p>

<p>Eventually I settled on using a combination of <link href="http://ro-oslib.sourceforge.net/">OSLib</link> and my own libraries &ndash; imaginatively called SFLib &ndash; based on it. Together, these have formed the basis of all of my software which has been started since 2000.</p>

<p>The aim of this guide is to give some help to those who are competent in C but have not used it when writing for the RISC&nbsp;OS desktop. It will also introduce the use of SFLib, which may be of interest to those writing Wimp software using OSLib.</p>

<p>Many thanks to all those on the <link href="https://www.riscosopen.org/forum/">ROOL Forums</link> who have answered my questions about the DDE and offered suggestions while I&rsquo;ve worked on this guide.</p>

<p>Let&rsquo;s include a link to an anonymous chapter <ref id="chap-start-basic" />, as well as <ref id="sect-start-basic-reg">a link to a chapter</ref> by some custom text.</p>

<section>
<title>Nested to Level 2</title>

<p>Here we are at a lower level?</p>

<p>Let&rsquo;s test the minus (&minus;) and multiplication (&times;) signs!</p>

<section>
<title>Down to level 3</title>

<p>This should be yet another level below?</p>

</section>
</section>

<section>
<title>At level 2 again!</title>

<p>We're still at a lower level, or should be</p>

</section>
</section>

<!-- chapterlist/ -->

</index>

<section>
<p>This comes before chapter 1.</p>
</section>

<chapter file="chapter1.xml&amp;some&amp;"/>

<section>
<p>This comes between chapters 1 and 2.</p>
</section>

<chapter file="file-structure.xml"/>

<section>
<p>This comes right at the end of the file.</p>
</section>

</manual>
